### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HuwCampbell** [icicle-lang/icicle#11]
- [x] Module system
- [ ] Removal of old parser
- [ ] Removal of old dictionaries, replaced with proper module 
- [ ] Let bindings to use the same Declarations and Functions
- [x] Regular expression support
